### ISSUE TITLE
Script does not work with Proxmox 7.3-6 and Ubuntu 22.04 container

### ISSUE THREAD

**Issue by GLehnhoff** [realashleybailey/nginx-proxy-manager-lxc#1]
Script does not work with Proxmox 7.3-6 and Ubuntu 22.04 container. See attachment.
![grafik](https://user-images.githubusercontent.com/5453201/221287855-b3bd5d46-8940-4acd-8416-8e8a068bd0eb.png)
I created the container by myself and used the wget-script.

**Comment by GLehnhoff** [comment]
# Solution
- 2GB Disk is to less. It has to been 3 GB.
- 512MB RAM is hard at the border. With the same in SWAP it works.

**Comment by realashleybailey** [comment]
@GLehnhoff Thank you for your insights, I have raised the defaults for the container to your recommended amounts
